title: Ctrl + Alt + Backspace
markdown: redcarpet

# Site settings
baseurl: ""
url: "http://ctrlaltbksp.eu"

# Language settings
lang: fr
timezone: Europe/Paris

# Build settings
markdown: kramdown
permalink: date
sass:
    style: :compressed
    sass_dir: css
    cache_location: /tmp/sass
