title: Ctrl + Alt + Backspace

# Site settings
baseurl: ""
url: "http://ctrlaltbksp.eu"

# Language settings
lang: fr
timezone: Europe/Paris

# Build settings
permalink: date
markdown: kramdown
kramdown:
    input: GFM
    header_offset: 2
    use_coderay: true
    hard_wrap: false
    coderay:
        coderay_wrap: div
        coderay_line_numbers: nil
        coderay_tab_width: 4
sass:
    style: :compressed
    sass_dir: css

