title: Ctrl + Alt + Backspace

# Site settings
baseurl: ""
url: "http://ctrlaltbksp.eu"

# Language settings
lang: fr
timezone: Europe/Paris

# Author vcard
author:
    full_name: Mickaël RAYBAUD-ROIG
    email: raybaudroigm@gmail.com

# Build settings
permalink: date
markdown: kramdown
kramdown:
    input: GFM
    header_offset: 2
    use_coderay: true
    hard_wrap: false
    coderay:
        coderay_wrap: div
        coderay_line_numbers: nil
        coderay_tab_width: 4
# Plugins settings
gems: ['jekyll-assets']
sass:
    style: :compressed
    sass_dir: css

assets:
    cache: true
    js_compressor: uglifier
    css_compressor: sass

