title: Ctrl + Alt + Backspace

# Site settings
baseurl: ""
url: "http://ctrlaltbksp.eu"

# Language settings
default_language: eo
timezone: Europe/Paris

# Author vcard
author:
    full_name: Mickaël RAYBAUD-ROIG
    email: raybaudroigm@gmail.com

# Build settings
permalink: date
# markdown: KramdownPygments
markdown: kramdown
kramdown:
    input: GFM
    header_offset: 1
    enable_coderay: false
    hard_wrap: false
exclude:
    - Makefile
    - Gemfile
    - Gemfile.lock

# Plugins settings
gems:
  - jekyll-assets
  - jekyll-language-plugin

language_data: data.languages.%%
language_includes_dir: _i18n
languages: ['fr', 'eo']

assets:
  compress:
    js:  true
    css: true
  features:
    liquid: false
    digest: true

flipmail_api_key: o3lzMgZ0dS6vdgL9qQNH